-- H2 in-memory schema for portable-ci (1.4.200 historical; 2.4.240 in CP-3A).
-- Execute only with MODE=Oracle and never against the Oracle profile.

CREATE SEQUENCE IF NOT EXISTS LAB_PEDIDO_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS LAB_ANEXO_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS LAB_PEDIDO (
  ID             DECIMAL(19, 0)  NOT NULL,
  NUMERO         VARCHAR(32)     NOT NULL,
  CLIENTE_NOME   VARCHAR(120)    NOT NULL,
  DESCRICAO      VARCHAR(500),
  VALOR_TOTAL    DECIMAL(15, 2)  NOT NULL,
  STATUS         VARCHAR(20)     DEFAULT 'NOVO' NOT NULL,
  CRIADO_EM      TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  ATUALIZADO_EM  TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_LAB_PEDIDO PRIMARY KEY (ID),
  CONSTRAINT UK_LAB_PEDIDO_NUMERO UNIQUE (NUMERO),
  CONSTRAINT CK_LAB_PEDIDO_VALOR CHECK (VALOR_TOTAL >= 0),
  CONSTRAINT CK_LAB_PEDIDO_STATUS
    CHECK (
      CASE STATUS
        WHEN 'NOVO' THEN TRUE
        WHEN 'APROVADO' THEN TRUE
        WHEN 'CANCELADO' THEN TRUE
        ELSE FALSE
      END
    )
);

CREATE TABLE IF NOT EXISTS LAB_ANEXO (
  ID             DECIMAL(19, 0)  NOT NULL,
  PEDIDO_ID      DECIMAL(19, 0)  NOT NULL,
  NOME_ARQUIVO   VARCHAR(255)    NOT NULL,
  TIPO_CONTEUDO  VARCHAR(127)    NOT NULL,
  TAMANHO_BYTES  DECIMAL(19, 0)  NOT NULL,
  SHA256         CHAR(64)        NOT NULL,
  CONTEUDO       BLOB            NOT NULL,
  CRIADO_EM      TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_LAB_ANEXO PRIMARY KEY (ID),
  CONSTRAINT FK_LAB_ANEXO_PEDIDO
    FOREIGN KEY (PEDIDO_ID) REFERENCES LAB_PEDIDO (ID),
  CONSTRAINT CK_LAB_ANEXO_TAMANHO CHECK (TAMANHO_BYTES >= 0),
  CONSTRAINT CK_LAB_ANEXO_SHA256
    CHECK (REGEXP_LIKE(SHA256, '^[0-9a-f]{64}$'))
);

CREATE INDEX IF NOT EXISTS IX_LAB_ANEXO_PEDIDO
  ON LAB_ANEXO (PEDIDO_ID);
