datasource.jndi-name=java:/jdbc/MigrationDS
datasource.pool-name=MigrationDS
profile.ci-h2.driver.name=h2-cp1d
profile.ci-h2.driver.module=com.h2database.h2.cp1d
profile.ci-h2.driver.class=org.h2.Driver
profile.oracle.driver.name=oracle
profile.oracle.driver.module=com.oracle.ojdbc7
profile.oracle.driver.class=oracle.jdbc.OracleDriver
