-- Oracle Database 19c. Idempotent creation for a dedicated laboratory schema.

DECLARE
  object_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO object_count
    FROM USER_SEQUENCES
   WHERE SEQUENCE_NAME = 'LAB_PEDIDO_SEQ';

  IF object_count = 0 THEN
    EXECUTE IMMEDIATE
      'CREATE SEQUENCE LAB_PEDIDO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;
END;
/

DECLARE
  object_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO object_count
    FROM USER_SEQUENCES
   WHERE SEQUENCE_NAME = 'LAB_ANEXO_SEQ';

  IF object_count = 0 THEN
    EXECUTE IMMEDIATE
      'CREATE SEQUENCE LAB_ANEXO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;
END;
/

DECLARE
  object_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO object_count
    FROM USER_TABLES
   WHERE TABLE_NAME = 'LAB_PEDIDO';

  IF object_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE LAB_PEDIDO (
        ID             NUMBER(19, 0)       NOT NULL,
        NUMERO         VARCHAR2(32 CHAR)   NOT NULL,
        CLIENTE_NOME   VARCHAR2(120 CHAR)  NOT NULL,
        DESCRICAO      VARCHAR2(500 CHAR),
        VALOR_TOTAL    NUMBER(15, 2)       NOT NULL,
        STATUS         VARCHAR2(20 CHAR)   DEFAULT 'NOVO' NOT NULL,
        CRIADO_EM      TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
        ATUALIZADO_EM  TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_LAB_PEDIDO PRIMARY KEY (ID),
        CONSTRAINT UK_LAB_PEDIDO_NUMERO UNIQUE (NUMERO),
        CONSTRAINT CK_LAB_PEDIDO_VALOR CHECK (VALOR_TOTAL >= 0),
        CONSTRAINT CK_LAB_PEDIDO_STATUS
          CHECK (STATUS IN ('NOVO', 'APROVADO', 'CANCELADO'))
      )
    ]';
  END IF;
END;
/

DECLARE
  object_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO object_count
    FROM USER_TABLES
   WHERE TABLE_NAME = 'LAB_ANEXO';

  IF object_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE LAB_ANEXO (
        ID             NUMBER(19, 0)       NOT NULL,
        PEDIDO_ID      NUMBER(19, 0)       NOT NULL,
        NOME_ARQUIVO   VARCHAR2(255 CHAR)  NOT NULL,
        TIPO_CONTEUDO  VARCHAR2(127 CHAR)  NOT NULL,
        TAMANHO_BYTES  NUMBER(19, 0)       NOT NULL,
        SHA256         CHAR(64 CHAR)        NOT NULL,
        CONTEUDO       BLOB                 NOT NULL,
        CRIADO_EM      TIMESTAMP(6)         DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_LAB_ANEXO PRIMARY KEY (ID),
        CONSTRAINT FK_LAB_ANEXO_PEDIDO
          FOREIGN KEY (PEDIDO_ID) REFERENCES LAB_PEDIDO (ID),
        CONSTRAINT CK_LAB_ANEXO_TAMANHO CHECK (TAMANHO_BYTES >= 0),
        CONSTRAINT CK_LAB_ANEXO_SHA256
          CHECK (REGEXP_LIKE(SHA256, '^[0-9a-f]{64}$', 'c'))
      )
    ]';
  END IF;
END;
/

DECLARE
  object_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO object_count
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IX_LAB_ANEXO_PEDIDO';

  IF object_count = 0 THEN
    EXECUTE IMMEDIATE
      'CREATE INDEX IX_LAB_ANEXO_PEDIDO ON LAB_ANEXO (PEDIDO_ID)';
  END IF;
END;
/
