-- Destructive but idempotent rollback for the dedicated laboratory schema.

DECLARE
  object_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO object_count FROM USER_TABLES WHERE TABLE_NAME = 'LAB_ANEXO';
  IF object_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE LAB_ANEXO PURGE';
  END IF;

  SELECT COUNT(*) INTO object_count FROM USER_TABLES WHERE TABLE_NAME = 'LAB_PEDIDO';
  IF object_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE LAB_PEDIDO PURGE';
  END IF;

  SELECT COUNT(*) INTO object_count
    FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'LAB_ANEXO_SEQ';
  IF object_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP SEQUENCE LAB_ANEXO_SEQ';
  END IF;

  SELECT COUNT(*) INTO object_count
    FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'LAB_PEDIDO_SEQ';
  IF object_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP SEQUENCE LAB_PEDIDO_SEQ';
  END IF;
END;
/
